---
space_code: jdj6k6
crontab_timestamp: '1511247743'
interface:
  upload_data: http://0.0.0.0:3000/survey_data/upload
  sync_corntab: http://0.0.0.0:3000/spaces/sync_crontab
  sync_emergency_treatment: http://0.0.0.0:3000/spaces/sync_emergency_treatment
  hartbit: http://0.0.0.0:3000/spaces/hartbit
commands:
  at: AT
  ate_close: ATE0
  ate_open: ATE1
  sleep_mode_close: AT%SLEEP=0
  sleep_mode_open: AT%SLEEP=0
  sim_setup: AT+CPIN?
  signal_intensity: AT+CSQ
  gsm_sign_in_prompt: AT+CREG=1
  gsm_signed_in: AT+CREG?
  gprs_sign_in_prompt: AT+CGREG=1
  gprs_signed_in: AT+CGREG?
  attachemnt: AT+CGATT=1
  attachemnt_ready: AT+CGATT?
  http_init: AT+HTTPINIT
  http_params_cid: AT+HTTPPARA="CID",1
  http_params_url: AT+HTTPPARA="URL",
  http_context: AT+HTTPPARA="CONTENT","application/json"
  http_package_size: AT+HTTPDATA=40,10000
  http_send: AT+HTTPACTION=1
  http_read: AT+HTTPREAD
  http_close: AT+HTTPTERM
