---
sim: true
space_code: 8a1isp
crontab_timestamp: '1516294805'
interface:
  upload_data: http://192.168.31.178:3000/survey_data/upload
  update_cmd_quota: http://192.168.31.178:3000/spaces/update_cmd_quota
  sync_crontab: http://192.168.31.178:3000/spaces/sync_crontab
  sync_activate: http://192.168.31.178:3000/spaces/sync_activate
  hartbit: http://192.168.31.178:3000/spaces/hartbit
  get_devise_list: http://192.168.31.178:3000/spaces/get_devise_list
  upload_node_online_state: http://192.168.31.178:3000/spaces/upload_node_online_state
commands:
  at: AT
  ate_close: ATE0
  ate_open: ATE1
  sleep_mode_close: AT%SLEEP=0
  sleep_mode_open: AT%SLEEP=0
  sim_setup: AT+CPIN?
  signal_intensity: AT+CSQ
  gsm_sign_in_prompt: AT+CREG=1
  gsm_signed_in: AT+CREG?
  gprs_sign_in_prompt: AT+CGREG=1
  gprs_signed_in: AT+CGREG?
  attachemnt: AT+CGATT=1
  attachemnt_ready: AT+CGATT?
  http_set_connection_gprs: AT+SAPBR=3,1,"Contype\","GPRS"
  http_set_apn: AT+SAPBR=3,1,"APN","CMNET"
  http_enable_gprs: AT+SAPBR=1,1
  http_disable_gprs: AT+SAPBR=0,1
  check_connection_get_ip: AT+SAPBR=2,1
  http_init: AT+HTTPINIT
  http_params_cid: AT+HTTPPARA="CID",1
  http_params_url: AT+HTTPPARA="URL",
  http_context: AT+HTTPPARA="CONTENT","application/json"
  http_package_size: AT+HTTPDATA=40,10000
  http_get_send: AT+HTTPACTION=0
  http_post_send: AT+HTTPACTION=1
  http_read: AT+HTTPREAD
  http_close: AT+HTTPTERM
cmd_quota_timestamp: '1512803265'
cmd_quota:
  th:
  - temp
  - humi
